### ISSUE TITLE
Consider using SHACL instead of OWL / RDFS for schema constraints

### ISSUE THREAD

**Issue by joepio** [terminusdb/terminusdb-server#123]
Let me start by saying: very impressive work! You guys have realized many of the ideas that I was pondering about in a nicely built, open source package. Awesome. Ok, to the issue.

Currently, TerminusDB uses the OWL (Web ontology language) + RDFS for storing the schema. I think OWL is might not be the right ontology, since it was designed not to validate graphs, but to provide reasoning abilities. For example, consider the ontology from the quickstart guide, and an example instance using the property wrongly:

```ttl
scm:journey_bicycle
  a owl:ObjectProperty ;
  rdfs:domain scm:Journey ;
  rdfs:label "Bicycle used";
  rdfs:range scm:Bicycle ;

example:suzanne
   a example:Person ;
   scm:journey_bicycle "I'm just trying to break things" ;
```

I'd assume we don't want this to happen. However, it's perfectly valid RDF, and a reasoner would conclude that `example:suzanne` is a Journey and the string "I'm just trying to break things" is a Bicycle. That's now what you'd probably have in mind - you probably wanted to say "If you use `scm:journey_bicycle`, make sure to put a `scm:Bicycle` on the right side!".

This has to do with how [`rdfs:domain`](https://www.w3.org/TR/rdf-schema/#ch_domain) and [`rdfs:range`](https://www.w3.org/TR/rdf-schema/#ch_range) are defined.

I've made the same mistake some time ago when modelling some OWL files using the Protege software... OWL is simply not built for constraining data - it's built for reasoning, for adding new triples, for drawing new conclusions. It's built with the Open World Assumption in mind, which assumes that all data that you put in the system is always correct. However, in practice, you _need to make sure_ that data conforms to some model before accepting it, because otherwise things will break. 

_However_, the more recent SHACL specification _does_ do what you're probably looking for: it provides a schema language for defining data shapes. These shapes are important when creating instances and rendering tables, because you need valid shape constrained data.

Of course, your implementation could interpret these rdfs / owl properties as type constraints, but keep in mind that their formal definitions are different, and they might make things awkward later on.

**Comment by kevinchekovfeeney** [comment]
Hi Joepio, 

Yes - in TerminusDB you have two different types of OWL graphs - one is schema and it applies a closed world interpretation to the logical structure, the other is an inference graph which uses traditional OWL open world inference semantics. 

We were involved tangentially in the SHACL specification - I was the coordinator of the ALIGNED project at the time - Dimitri Konstakostas was one of the main people behind SHACL and part of ALIGNED at the time. Gavin wrote a variety of proofs of inconsisitencies in SHACL and for a variety of reasons, we came to the conclusion that it was far inferior to just using OWL in a closed world regime - OWL has the benefit of having a really well thought out logical underpinning, well defined complexities and so on - SHACL not so much.

**Comment by GavinMendelGleason** [comment]
Reiterating some of what Kevin said above for clarity: We treat OWL in two distinct reasoning regimes. In both reasoning regimes we take the unique names assumption (also a divergence from the OWL standard).

1. The first is a closed-world reasoning constraint regime. We do not make any inferences about what logical rules should hold, we only check to see if the ones that are asserted are self-consistent and consistent with the information in the corresponding instance graph.

2. The second is a more traditional inference regime. We expand what can be inferred about the logical statements in the contraint ontology based on information asserted as inferential. These expanded logical statements can then take part in the constraining of information in the instance graph.

The advantage of this approach is that we can specify constraints and inference in a single uniform language. In practice we spend almost all of our energy on the constraint aspects as this is what is most useful for a database, although we do make use of inferencing for various things in the core system graph (transitivity etc).

We evaluated SHACL but ultimately felt that it was not sufficiently well defined (negation with cardinalities led to non-monotonic functors which can not be the basis of an inductive definition) and did not add much extra over the constraint interpretation of OWL and had the downside of requiring two languages rather than one. 

We do lack the ability to specify inductive relationships clearly in OWL and I'd like to see this rectified. But given that the SHACL definition was inconsistent and they did not distinguish between greatest and least fixed-points, I think there is more work to be done to make this viable anyhow.

**Comment by joepio** [comment]
Thanks for the clarification and the quick reply! You've obviously put way more thought into this than I anticipated.

I understand the value of using a mathematically / logically consistent ontology, and combining inferencing and shape validation into a single model seems reasonable, too.

I'll take a better look at your implementation to understand how you actually interpreted RDF / OWL. I'll close this for now.
