### ISSUE TITLE
Single binary without any dependencies.

### ISSUE THREAD

**Issue by ansarizafar** [terminusdb/terminusdb-server#30]
Developers are eagerly waiting for a modern, easy to use and manage database. It would be great If Terminusdb is released as a single binary without any other dependencies or requiring developers to install Docker.  New storage engine is written in Rust lang, why not just also develop Terminusdb server in Rust lang and release it as a single binary.

I would also like to suggest a twitter account and discord server for community support.

**Comment by rrooij** [comment]
I agree with the need for a single binary or an easier installation option. I've already been researching the possibility to create a PPA repo and a RPM repo which makes installing easier. The advantage over a static binary is that you get updates from your package manager.

However, a single binary would be nice to try things out. We will definitely look into it.

The chance of a Rust port becoming a thing is very slim though. Prolog is used specifically because the predicate logic programming is a very good match for our database software (for instance, constraint checking with logical rules). So it probably won't be ported to Rust.

**Comment by ansarizafar** [comment]
I don't know anything about Prolog but in my opinion a database is a critical piece and must be written in a system language for better performance and efficient CPU/Memory usage.

I would definitely like to play with Terminusdb, When a single binary or an easier installation option will be available. Terminusdb has unusual Schema/query language syntax so a step by step tutorial for designing database schema/queries, access permissions, migrations and Back/restore  for a common use case like a blogging app will really help developers new to Terminusdb. I know Terminusdb is different than other databases but developers needs a simpler schema/query language like https://edgedb.com/roadmap or Prisma2 https://github.com/prisma/prisma2

**Comment by ansarizafar** [comment]
Is there any new update/ETA regarding Single binary for Terminusdb?

**Comment by ansarizafar** [comment]
A new version of Terminusdb is just released. Is there any chance of Single binary release for Ubuntu?

**Comment by ansarizafar** [comment]
@rrooij I am still waiting for a Single binary release to try out amazing Terminusdb.

**Comment by rrooij** [comment]
@ansarizafar Hey, sorry for the late reply. A lot of work has to be done and the single binary is definitely one of them. It is on the list we don't have a ETA yet.

Meanwhile, the easiest way to try terminusdb is probably the heroku deploy.

https://github.com/terminusdb/terminus-heroku

**Comment by ansarizafar** [comment]
@rrooij Single binary or an easier installation option will allow more developers to try terminusdb and more users means possibly more contributors. I request you to place this higher on your priorities list.

**Comment by rrooij** [comment]
This has been solved by the release of terminusdb-desktop. See:

https://terminusdb.com/hub/download
