### ISSUE TITLE
Graphql support

### ISSUE THREAD

**Issue by ansarizafar** [terminusdb/terminusdb-server#35]
Is there any plan to support Graphql like https://www.topquadrant.com/technology/graphql/?

**Comment by marvin-hansen** [comment]
GraphQL support is paramount for industry adoption. Take an inspiration from DGraph that generates it's GraphQL API from the DB schema:

https://graphql.dgraph.io/docs/api/

**Comment by kevinchekovfeeney** [comment]
No plans to implement this - GraphQL is more of a document templating language / means of organizing APIs than a query language - DGraph have had to extend it so that it's no longer actually GraphQL removing all the interoperability benefits and just leaving them with an awkward query language adapted from a REST API templating thing.  Not impossible that we might one day produce document APIs in vanilla GraphQL but not on the roadmap

**Comment by Tails** [comment]
Might be happening afterall: https://github.com/terminusdb/terminusdb/issues/1488
